[project]
name = "anki-change-font-size"
version = "0.1.0"
description = "Anki add-on to change font size"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aqt>=25.9.2",
    "pyright>=1.1.406",
    "ruff>=0.14.1",
]
