version: '3'

tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list-all
    silent: true

  package:
    desc: Package add-on
    silent: true
    cmds:
      - zip -r release/change_font_size.ankiaddon * -x "release/*" -x "Taskfile.yaml"